#
# Capture all traffic.
#
# Priority of this rule is less than ingress-app, that rule will happen first.
#

# https://doc.traefik.io/traefik/routing/providers/kubernetes-crd/
# https://doc.traefik.io/traefik/routing/routers/

apiVersion: 'traefik.containo.us/v1alpha1'
kind: 'IngressRoute'

metadata:
  name: '{{ .Release.Name }}-web-patient'

spec:
  entryPoints:
    - 'websecure'
  routes:
    - kind: 'Rule'
      match: 'HostRegexp(`{{ or .Values.hostPatient .Values.hostFlask }}`)'
      priority: 100
      services:
        - kind: 'Service'
          name: {{ .Values.serviceWebPatient | squote }}
          port: 8000
  tls:
    secretName: {{ .Values.tlsSecret | squote }}
