apiVersion: 'cert-manager.io/v1'
kind: 'Certificate'

metadata:
  name: 'cert-uwscope-org'

spec:
  commonName: 'uwscope.org'
  secretName: 'tls-uwscope-org'
  dnsNames:
    - 'uwscope.org'
    - 'www.uwscope.org'
  issuerRef:
    name: 'letsencrypt'
    kind: 'ClusterIssuer'
