apiVersion: 'apps/v1'
kind: 'Deployment'

metadata:
  name: '{{ .Release.Name }}-deployment-nothing'

spec:
  replicas: 1
  selector:
    matchLabels:
      app: '{{ .Release.Name }}-nothing'
  template:
    metadata:
      labels:
        app: '{{ .Release.Name }}-nothing'
    spec:
      containers:
        - name: '{{ .Release.Name }}-nothing'
          image: 'nginx:alpine'
          imagePullPolicy: 'Always'
          ports:
            - containerPort: 80
          volumeMounts:
            - name: '{{ .Release.Name }}-deployment-nothing-volume-nginx-conf'
              mountPath: '/etc/nginx/conf.d/'
      volumes:
        - name: '{{ .Release.Name }}-deployment-nothing-volume-nginx-conf'
          configMap:
            name: '{{ .Release.Name }}-deployment-nothing-configmap-nginx-conf'

---

apiVersion: 'v1'
kind: 'ConfigMap'
metadata:
  name: '{{ .Release.Name }}-deployment-nothing-configmap-nginx-conf'
data:
  default.conf: |
    server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;

        # Default to returning a successful nothing for most paths
        location / {
            return 204;
        }

        # Return a 403 Forbidden when asked
        location /forbidden/ {
            return 403;
        }
    }
