#
# Redirect all traffic from the web entrypoint that attempts to access /api/.
#
# Redirect to an error so this will fail fast.
# Priority of this rule is greater than ingress-redirect-http-web, this rule will happen first.
#

# https://doc.traefik.io/traefik/middlewares/redirectscheme/

apiVersion: 'traefik.containo.us/v1alpha1'
kind: 'Middleware'

metadata:
  name: '{{ .Release.Name }}-redirect-http-app-middleware'

spec:
  replacePath:
    # The nothing service is configured to provide a 403 Forbidden
    path: '/forbidden/'

---

# https://doc.traefik.io/traefik/routing/providers/kubernetes-crd/
# https://doc.traefik.io/traefik/routing/routers/

apiVersion: 'traefik.containo.us/v1alpha1'
kind: 'IngressRoute'

metadata:
  name: '{{ .Release.Name }}-redirect-http-app-route'

spec:
  entryPoints:
    - 'web'
  routes:
    - kind: 'Rule'
      match: 'HostRegexp(`{any:.+}`) && PathPrefix(`/api/`)'
      priority: 10000
      middlewares:
        - name: '{{ .Release.Name }}-redirect-http-app-middleware'
      # Provide a service so the route is valid, but all traffic is caught by the middleware.
      # Without this, the route will not be applied. Use nothing service for this purpose.
      services:
        - kind: 'Service'
          name: '{{ .Release.Name }}-nothing'
          port: 8000
