#
# Redirect all traffic from the web entrypoint to instead use SSL.
#
# Priority of this rule is less than ingress-redirect-http-app, that rule will happen first.
#

# https://doc.traefik.io/traefik/middlewares/redirectscheme/

apiVersion: 'traefik.containo.us/v1alpha1'
kind: 'Middleware'

metadata:
  name: '{{ .Release.Name }}-redirect-http-web-middleware'

spec:
  redirectScheme:
    scheme: 'https'
    permanent: true
    port: '443'

---

# https://doc.traefik.io/traefik/routing/providers/kubernetes-crd/
# https://doc.traefik.io/traefik/routing/routers/

apiVersion: 'traefik.containo.us/v1alpha1'
kind: 'IngressRoute'

metadata:
  name: '{{ .Release.Name }}-redirect-http-web-route'

spec:
  entryPoints:
    - 'web'
  routes:
    - kind: 'Rule'
      match: 'HostRegexp(`{any:.+}`)'
      priority: 100
      middlewares:
        - name: '{{ .Release.Name }}-redirect-http-web-middleware'
      # Provide a service so the route is valid, but all traffic is caught by the middleware.
      # This simply prevents Traefik from generating errors based on the route.
      #
      # TODO: This should not depend on an external service
      services:
        - kind: 'Service'
          name: 'scope-web'
          port: 3000
