apiVersion: 'v1'
kind: 'Service'

metadata:
  name: '{{ .Release.Name }}-nothing'

spec:
  selector:
    app: '{{ .Release.Name }}-nothing'
  ports:
    - port: 8000
      targetPort: 80
      protocol: 'TCP'
