#
# Service, Deployment, and ConfigMap for server_flask.
#

---

apiVersion: "v1"
kind: "Service"
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app: "{{ .Release.Name }}"

spec:
  selector:
    app: "{{ .Release.Name }}"
  ports:
    - port: 8000
      targetPort: 4000
      protocol: "TCP"

---

apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "{{ .Release.Name }}-deployment"
  labels:
    app: "{{ .Release.Name }}"

spec:
  # TODO: Current 1 replica because of internal state, increase when stateless
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}"
    spec:
      containers:
        - name: "{{ .Release.Name }}"
          image: {{ (printf "%s/%s:%s" .Values.registryUrl .Values.imageName .Values.imageTag) | quote }}
          imagePullPolicy: "Always"
          ports:
            - containerPort: 4000
          volumeMounts:
            - name: "{{ .Release.Name }}-config"
              mountPath: "/cloned_repository/server_flask/instance/"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
      volumes:
        - name: "{{ .Release.Name }}-config"
          configMap:
            name: "{{ .Release.Name }}-configmap-config"
      imagePullSecrets:
        - name: "{{ .Release.Name }}-secret-image-pull"

---

apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "{{ .Release.Name }}-configmap-config"
data:
  flask_config.yaml: |
{{ .Values.flaskConfig | toYaml | indent 4 }}
