# Path to the Helmfile relative to location of this helmfile-config.yaml
helmfile: 'helmfile.yaml'

# Dependencies to be uploaded so they can be referenced as local files
dependencies:
  - file: '../../.staging/helm_repo/scope-flask-server-0.1.0.tgz'
    destination: './charts/scope-flask-server.tgz'
  - file: '../../.staging/helm_repo/scope-web-patient-0.1.0.tgz'
    destination: './charts/scope-web-patient.tgz'
  - file: '../../.staging/helm_repo/scope-web-registry-0.1.0.tgz'
    destination: './charts/scope-web-registry.tgz'
  - file: '../../.staging/helm_repo/scope-ingress-0.1.0.tgz'
    destination: './charts/scope-ingress.tgz'
  - file: '../../.staging/helm_repo/scope-instance-ingress-0.1.0.tgz'
    destination: './charts/scope-instance-ingress.tgz'
