apiVersion: 'apps/v1'
kind: 'Deployment'
metadata:
  name: 'deployment-{{ .Release.Name }}'
  labels:
    app: '{{ .Release.Name }}'

spec:
  # TODO: Current 1 replica because of internal state, increase when stateless
  replicas: 1
  selector:
    matchLabels:
      app: '{{ .Release.Name }}'
  template:
    metadata:
      labels:
        app: '{{ .Release.Name }}'
    spec:
      containers:
        - name: 'scope-app'
          image: '{{ printf "%s/%s:%s" .Values.registryUrl .Values.imageName .Values.imageTag }}'
          imagePullPolicy: 'Always'
          ports:
            - containerPort: 4000
          resources:
            limits:
              cpu: '100m'

      imagePullSecrets:
        - name: 'secret-image-pull-{{ .Release.Name }}'
