# https://doc.traefik.io/traefik/routing/providers/kubernetes-crd/
# https://doc.traefik.io/traefik/routing/routers/

apiVersion: 'traefik.containo.us/v1alpha1'
kind: 'Middleware'

metadata:
  name: 'ingress-scope-app-stripprefix'
  labels:
    app: 'scope-app'

spec:
  stripPrefix:
    prefixes:
      - '/api'
    forceSlash: false

---

apiVersion: 'traefik.containo.us/v1alpha1'
kind: 'IngressRoute'

metadata:
  name: 'ingress-scope-app'
  labels:
    app: 'scope-app'

spec:
  entrypoints:
    - 'web'
  routes:
    - kind: 'Rule'
      match: 'PathPrefix(`/api`)'
      priority: 10000
      middlewares:
        - name: 'ingress-scope-app-stripprefix'
      services:
        - kind: 'Service'
          name: 'scope-app'
          port: 4000
