apiVersion: 'v1'
kind: 'Secret'
metadata:
  name: '{{ .Release.Name }}-secret-image-pull'

type: 'kubernetes.io/dockerconfigjson'
data:
  .dockerconfigjson: {{ (include "secretImagePullEncoded" .) | squote }}
